// Auth
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// For analsis actions
export const LOADING = "LOADING";
export const LOADING_COMPLETE = "LOADING_COMPLETE";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_ERROR = "UPLOAD_ERROR";
export const INITIAL_PLOT_SUCCESS = "INITIAL_PLOT_SUCCESS";
export const INITIAL_PLOT_ERROR = "INITIAL_PLOT_ERROR";
export const STATIONARITY_TEST_SUCCESS = "STATIONARITY_TEST_SUCCESS";
export const STATIONARITY_TEST_ERROR = "STATIONARITY_TEST_ERROR";
export const PLOT_AVERAGE_SUCCESS = "PLOT_AVERAGE_SUCCESS";
export const PLOT_AVERAGE_ERROR = "PLOT_AVERAGE_ERROR";
export const LOAD_AVERAGE_SUCCESS = "LOAD_AVERAGE_SUCCESS";
export const LOAD_AVERAGE_ERROR = "LOAD_AVERAGE_ERROR";
export const CORELATION_PLOT_SUCCESS = "CORELATION_PLOT_SUCCESS";
export const CORELATION_PLOT_ERROR = "CORELATION_PLOT_ERROR";
export const DECOMPOSE_PLOT_SUCCESS = "DECOMPOSE_PLOT_SUCCESS";
export const DECOMPOSE_PLOT_ERROR = "DECOMPOSE_PLOT_ERROR";
export const TRAIN_ARIMA_SUCCESS = "TRAIN_ARIMA_SUCCESS";
export const TRAIN_LSTM_SUCCESS = "TRAIN_LSTM_SUCCESS";
export const TRAIN_LSTM_ERROR = "TRAIN_LSTM_ERROR";
export const TRAIN_ARIMA_FALIURE = "TRAIN_ARIMA_FALIURE";
export const AUTO_ARIMA_SUCCESS = "AUTO_ARIMA_SUCCESS";
export const AUTO_ARIMA_ERROR = "AUTO_ARIMA_ERROR";
export const FORECAST_SUCCESS = "FORECAST_SUCCESS";
export const FORECAST_ERROR = "FORECAST_ERROR";